name: train-pipeline

on:
  schedule:
    #- cron: '0 9 * * 1'   # Todos los lunes a las 8am UTC
  workflow_dispatch:

jobs:
  run-train-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Train Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python src/pipelines/training_pipeline/training_pipeline.py